version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
deploy:
  machine:
    enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - "cd:75:02:1d:fe:ec:ea:4b:6d:72:7d:ff:68:6f:dc:41"
    - checkout
    - run:
        name: Push Master to Production
        command: |
          git push https://github.com/beel7595/scheduler.git master:circleci-project-setup
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: circleci-project-setup
      - deploy:
          filters:
            branches:
              ignore: circleci-project-setup
          requires:
            - build
      



     

